### ISSUE TITLE
Applies UI changes but not transparency

### ISSUE THREAD

**Issue by Grey421** [Mephiles-the-Dark/Better_Discord#1]
![image](https://user-images.githubusercontent.com/52113147/75471025-82ea3480-5989-11ea-9680-e57079afba79.png)

**Comment by Mephiles-the-Dark** [comment]
You are better off finding me on Discord or joining the Better Discord servers.  I created this repo, so I could have a base theme file, but I had troubles figuring out how to host it.  

Ме́филес#9198 (376086802961793024)
