### ISSUE TITLE
Not working on 1/11 for some reason

### ISSUE THREAD

**Issue by Muhanad-byte** [Mephiles-the-Dark/Better_Discord#3]
( Does not work on 1/11 probably because of a discord update or smth )
i can't use discord without this theme >:

**Comment by Ecconia** [comment]
Same here.

Version:
- Stable 110451 (c233a73)
- Host 0.0.16
(Linux)

**Comment by Mephiles-the-Dark** [comment]
Themes that use back layers need a "theme fixer" after the major update.  You may have noticed my weekly update stopped last month.  I need to install Better Discord on my new computer.  Will get it fixed after Canary is functional with Better Discord.

**Comment by Muhanad-byte** [comment]
Looks good !, I've tried looking for alternatives but yours is way smoother and cleaner + the brightness affect that happens when the mouse cursor gets out of the app is decent !

**Comment by Mephiles-the-Dark** [comment]
It is going to be some more time, I want to get it polished.

**Comment by Muhanad-byte** [comment]
Tyt <3

**Comment by Mephiles-the-Dark** [comment]
I put in a partial update.  Do not expect any more changes until next week.  Also, going to close the issue with this update.
